In [1]:
1 + 2

3

In [3]:
for _ in range (5)
    print ("fuck u")

SyntaxError: invalid syntax (<ipython-input-3-43d0b08ab0b5>, line 1)

In [6]:
for _ in range (5):
    print ("fuck u")

fuck u
fuck u
fuck u
fuck u
fuck u


欢迎你



In [ ]:
data  = [i*2 for i in range(100)]

In [7]:
len(data)

NameError: name 'data' is not defined

In [8]:
data = [i*2 for i in range(100)]
len(data)

100

In [9]:
data[-1]

198

In [10]:
data(:10)

SyntaxError: invalid syntax (<ipython-input-10-73287f357e46>, line 1)

In [11]:
data[:10]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [1]:
%run myScript/hello.py


hello Machine Learning !


In [2]:
hello("elory")

hello elory !


In [3]:
import mymodule.FirstML

ModuleNotFoundError: No module named 'mymodule.FirstML'

In [4]:
import mymodule

In [5]:
mymodule.predict(1)

AttributeError: module 'mymodule' has no attribute 'predict'

In [6]:
from  mymodule import FirstML

FirstML.predict(2)

ImportError: cannot import name 'FirstML' from 'mymodule' (/Users/Elroy/Desktop/machine-learning/mymodule/__init__.py)

In [7]:
%timeit L = [i**2 for i in range (1000)]

341 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit L = [i**2 for i in range (10000)]

3.33 ms ± 86.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
from mymodule import FirstML

In [10]:
FirstML.predict(2)

?


# %%timeit   测试一段代码

In [1]:
%%timeit
L = []
for n in range(1000):
    L.append(n**2)

365 µs ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# %time

In [2]:
%time L = [i**2 for i in range (1000)]

CPU times: user 300 µs, sys: 1e+03 ns, total: 301 µs
Wall time: 303 µs


In [4]:
%%time
L =[]
for i in range(100000):
    L.append(i**2)

CPU times: user 70.4 ms, sys: 4.67 ms, total: 75.1 ms
Wall time: 84.3 ms


In [5]:
import random
L=[random.random() for i in range(100000)]
%timeit L

28.2 ns ± 1.48 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [6]:
L = [random.random() for i in range(100000)]
%time L.sort()

CPU times: user 28.5 ms, sys: 697 µs, total: 29.2 ms
Wall time: 44.4 ms


In [7]:
%time L.sort()

CPU times: user 5.07 ms, sys: 171 µs, total: 5.24 ms
Wall time: 5.98 ms


# 其他魔法命令

In [8]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%

# numpy.array 基础

In [9]:
import numpy

In [10]:
numpy.__version__

'1.18.1'

In [11]:
import numpy as np

In [12]:
np.__version__

'1.18.1'

# python List的特点

In [13]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
L[5]

5

In [17]:
L[5]=100


In [18]:
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [19]:
L[5]="Machine learning"
L

[0, 1, 2, 3, 4, 'Machine learning', 6, 7, 8, 9]

In [20]:
import array

In [21]:
arr = array.array('i',[i for i in range(10)])

In [22]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[5]

5

In [24]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[5]='machine learning'

TypeError: an integer is required (got type str)

arr 限定类型  只能存储一种类型

# numpy.array

In [27]:
nparr = np.array([i for i in range(10)])

In [28]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
nparr[5]=100
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [30]:
nparr[5]='machine learning'

ValueError: invalid literal for int() with base 10: 'machine learning'

numpy.array 限定存储一种类型

In [31]:
nparr.dtype

dtype('int64')

In [32]:
nparr[5]=5.0
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
nparr[3]=3.14
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

整形传值浮点数   会自动变整形

In [35]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

# 其他创建numpy.array的方法

In [37]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(10).dtype

dtype('float64')

In [39]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.zeros(shape=(3,5),dtype=int)#三行五列  全0  dtype选择是int还是float

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [44]:
np.full(shape=(3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

# arange

In [45]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [46]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# linspace

In [49]:
np.linspace(0,20,10)切分20个等长段  等差数列

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [50]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [51]:
np.random.randint(0,10)

9

In [52]:
np.random.randint(0,10,10)

array([3, 9, 6, 0, 9, 6, 4, 5, 2, 1])

In [53]:
np.random.randint(4,8,size=10)

array([6, 4, 4, 6, 6, 5, 5, 4, 6, 7])

In [54]:
np.random.randint(4,8,size=(3,5))随机矩阵

array([[6, 7, 7, 6, 6],
       [6, 4, 5, 6, 5],
       [5, 4, 4, 6, 4]])

In [55]:
np.random.randint(4,8,size=(3,5))

array([[5, 4, 4, 4, 7],
       [4, 6, 5, 6, 7],
       [7, 6, 5, 6, 4]])

In [56]:
np.random.seed(666)

In [57]:
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [58]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [59]:
np.random.random()随机生成0到1之间的 浮点数

0.2811684913927954

In [64]:
np.random.random(10)

array([0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ,
       0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949])

In [65]:
np.random.random((3,5))

array([[0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981],
       [0.75366384, 0.66673747, 0.87287954, 0.52109719, 0.75020425],
       [0.32940234, 0.29130197, 0.00103619, 0.6361797 , 0.97933558]])

In [66]:
np.random.normal()

-0.19206285136190387

In [67]:
np.random.normal(10,100)

88.61128430284393

In [68]:
np.random.normal(10,100)

-159.04631420698095

In [69]:
np.random.normal(0,1,(3,5))

array([[-0.98873907,  0.31398563,  0.39638567,  0.57656584, -0.07019407],
       [ 0.91250436,  1.00470497,  0.41859929, -1.52902454,  0.92487532],
       [ 0.18305429,  0.34543496, -0.8131543 ,  1.06325382,  0.25866385]])

In [70]:
np.random.normal?

### numpy array基本属性

In [2]:
import numpy as np
x= np.arange(15).reshape(3,5)

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
x.ndim

2

In [5]:
x.shape  格式

(3, 5)

In [6]:
x.size   元素个数

15

numpy.array的数据访问

In [7]:
x


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
x[0]

array([0, 1, 2, 3, 4])

In [9]:
x[0][0]

0

In [46]:
y=np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
y[1]

1

In [23]:
y[0:5]  

[0, 1, 2, 3, 4]

In [24]:
y[3:]

[3, 4, 5, 6, 7, 8, 9]

In [26]:
x[:2,:3]   前两行前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [27]:
x[:2,::2]  前两行  间隔为2 遍历

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
x[::-1,::-1]   矩阵反转

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
x[0]

array([0, 1, 2, 3, 4])

In [30]:
x[0,:]

array([0, 1, 2, 3, 4])

In [31]:
x[:,0] 取一列

array([ 0,  5, 10])

In [32]:
subx = x[:2,:3]

In [33]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subx[0,0]=100      修改子矩阵的值也会使得原矩阵的值改变
subx 

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
x

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [36]:
x[0,0]=0          修改原矩阵 子矩阵的值也会改变
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
subx

array([[0, 1, 2],
       [5, 6, 7]])

In [38]:
subx=x[:2,:3].copy()    利用copy方法 使得子矩阵与原矩阵无关  修改数值也不会互相影响
subx

array([[0, 1, 2],
       [5, 6, 7]])

#### reshape

In [39]:
x.shape

(3, 5)

In [41]:
x.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
B= y.reshape(1,10)   变成二维数组
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
x.reshape(15,-1) 指定行数  列数计算机自动分配

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [50]:
y.reshape(-1,10)   十列 行数计算机分配

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
x.reshape(3,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 合并操作

In [53]:
x = np.array([1,2,3])
y = np.array([3,2,1])
x


array([1, 2, 3])

In [54]:
y

array([3, 2, 1])

In [55]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [57]:
z=np.array([666,666,666])
z

array([666, 666, 666])

In [58]:
np.concatenate([x,y,z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [61]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

concatenate 只能处理维度相同的矩阵

In [64]:
np.concatenate([a,z]) z维度是1

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [65]:
np.concatenate([a,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [66]:
np.vstack([a,z])   vstack维度不同也可以自动拼接

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [67]:
b=np.full((2,2),100)
b

array([[100, 100],
       [100, 100]])

In [68]:
np.hstack([a,b])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割操作

In [70]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
x1,x2,x3=np.split(x,[3,7])

In [75]:
x1

array([0, 1, 2])

In [76]:
x2

array([3, 4, 5, 6])

In [77]:
x3

array([7, 8, 9])

In [78]:
x1,x2=np.split(x,[5])

In [79]:
x1

array([0, 1, 2, 3, 4])

In [80]:
x2

array([5, 6, 7, 8, 9])

In [81]:
A = np.arange(16).reshape(4,4)

In [82]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
A1,A2 = np.split(A,[2])

In [85]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [86]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
A1,A2 = np.split(A,[2],axis=1)

In [88]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [89]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [90]:
upper,lower = np.vsplit(A,[2])

In [91]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
left,right = np.hsplit(A,[2])

In [96]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [97]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [102]:
head,last = np.hsplit(A,[-1])   [-1]表示把最后一列或最后一行赋值给参数

In [103]:
head

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [104]:
last

array([[ 3],
       [ 7],
       [11],
       [15]])

# numpy.array中的运算
给定一个向量，向量中每个数乘2
a=[0,1,2]
a*2= [0.2.4]

In [105]:
n = 10


In [107]:
2*L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
%%time
a = []
for e in L:
    a.append(a*2)


CPU times: user 8 µs, sys: 1e+03 ns, total: 9 µs
Wall time: 11 µs


In [112]:
%%time
a = [2*e for e in L]

CPU times: user 9 µs, sys: 1e+03 ns, total: 10 µs
Wall time: 12.9 µs


In [119]:
import numpy as np
L = np.arange(n)
L

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
%%time
a = np.array(2*e for e in L)

CPU times: user 47 µs, sys: 371 µs, total: 418 µs
Wall time: 2.1 ms


In [115]:
%%time
a =2*L

CPU times: user 43 µs, sys: 112 µs, total: 155 µs
Wall time: 385 µs


In [116]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## universal Functions

In [121]:
x=np.arange(1,16).reshape((3,5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [123]:
x+1


array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [124]:
x*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [125]:
x/2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [126]:
x//2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [127]:
x**2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [128]:
1/x   取到数

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [129]:
np.abs(x)  绝对值

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [130]:
np.sin(x)  正弦余弦

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [131]:
np.log2(x)   取对数

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

### 矩阵运算

In [132]:
a = np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [133]:
b = np.full((2,2),10)
b

array([[10, 10],
       [10, 10]])

In [134]:
a +b

array([[10, 11],
       [12, 13]])

In [135]:
a*b  对应位置元素相乘  不是标准矩阵乘法规则

array([[ 0, 10],
       [20, 30]])

In [136]:
a.dot(b)  标准矩阵乘法

array([[10, 10],
       [50, 50]])

In [138]:
a.T   求转置矩阵

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [139]:
v=np.array([1,2])

In [140]:
a

array([[0, 1],
       [2, 3]])

In [141]:
a+v

array([[1, 3],
       [3, 5]])

In [142]:
np.vstack([v]*a.shape[0]) +a

array([[1, 3],
       [3, 5]])

In [145]:
np.tile(v,(2,1))

array([[1, 2],
       [1, 2]])

In [146]:
np.tile(v,(2,1))+a

array([[1, 3],
       [3, 5]])

In [147]:
v

array([1, 2])

In [148]:
a

array([[0, 1],
       [2, 3]])

In [149]:
v*a

array([[0, 2],
       [2, 6]])

In [150]:
v.dot(a)

array([4, 7])

In [151]:
a.dot(v)

array([2, 8])

### 矩阵的逆矩阵

In [152]:
a

array([[0, 1],
       [2, 3]])

In [157]:
inva = np.linalg.inv(a)   求逆矩阵

In [158]:
a.dot(inva)

array([[1., 0.],
       [0., 1.]])

In [159]:
inva.dot(a)

array([[1., 0.],
       [0., 1.]])

####方阵才可以求逆矩阵  不是方阵只能求伪逆矩阵

In [160]:
x = np.arange(16).reshape((2,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [161]:
np.linalg.inv(x)  不是方阵求逆矩阵 报错

LinAlgError: Last 2 dimensions of the array must be square

In [169]:
pinvx = np.linalg.pinv(x)

In [170]:
pinvx

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [171]:
pivx.shape

(8, 2)

In [172]:
x.dot(pinvx)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

# 聚合操作

In [173]:
import numpy as np
l = np.random.random(100)

In [174]:
l

array([0.60241206, 0.4696098 , 0.89252264, 0.67179251, 0.2805891 ,
       0.48557352, 0.18941914, 0.77300465, 0.27895352, 0.44369436,
       0.05921629, 0.35817387, 0.39001778, 0.97294087, 0.66666496,
       0.43222954, 0.29779636, 0.12764388, 0.46036973, 0.15076875,
       0.25304989, 0.49806092, 0.69303536, 0.35143295, 0.70809416,
       0.45314547, 0.77706248, 0.79621201, 0.94598114, 0.31037084,
       0.13140848, 0.89806787, 0.1157424 , 0.23238228, 0.08503654,
       0.52986441, 0.53941242, 0.59312941, 0.84381828, 0.44627399,
       0.71284101, 0.04686105, 0.15806483, 0.98557716, 0.64354255,
       0.51415148, 0.5468195 , 0.13540188, 0.1731378 , 0.30603151,
       0.8374746 , 0.47208457, 0.21219716, 0.53434886, 0.59055228,
       0.51856775, 0.48087804, 0.2367665 , 0.46767775, 0.98238737,
       0.13726927, 0.63274072, 0.86887646, 0.78370063, 0.9854753 ,
       0.11918826, 0.8480523 , 0.83422871, 0.68775854, 0.16660285,
       0.61773378, 0.50341143, 0.70030395, 0.08758032, 0.78674

In [175]:
sum(l)

48.863389168747005

In [176]:
np.sum(l)

48.863389168747005

In [177]:
big_array = np.random.random(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

19.7 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
55.5 µs ± 4.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [178]:
np.min(big_array)

2.342439934133189e-06

In [180]:
np.max(big_array)

0.9999991874914148

In [181]:
x= np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [182]:
np.sum(x)   将所有元素聚合

120

In [183]:
np.sum(x,axis=0)    每一列的和

array([24, 28, 32, 36])

In [184]:
np.sum(x,axis=1)    每一行的和

array([ 6, 22, 38, 54])

In [185]:
np.prod(x)    所有元素的乘积

0

In [186]:
np.prod(x+1)     所有元素加一的乘积

20922789888000

In [187]:
np.mean(x)   平均值

7.5

In [188]:
np.median(x)   中位数

7.5

In [190]:
v= np.array([1,1,2,2,10])
np.mean(v)

3.2

In [191]:
np.median(v)      中位数有时候更能表示数据平均情况

2.0

In [194]:
np.percentile(big_array,q=50)

0.49717897725803256

In [195]:
np.percentile(big_array,q=100)

0.9999991874914148

In [197]:
for percent in (0,25,50,75,100):
    print(np.percentile(big_array,q=percent))

2.342439934133189e-06
0.24724296306147986
0.49717897725803256
0.745876137751833
0.9999991874914148


In [198]:
np.var(big_array)   方差

0.0832406295036947

In [199]:
np.std(big_array)  标准差

0.28851452217123263

In [205]:
x= np.random.normal(0,1,size = 1000000)  random.normal 正态分布的随机数

In [206]:
np.mean(x)

0.0013408796279592078

In [207]:
np.std(x)

1.0001618381438244

# 索引

In [2]:
import numpy as np
x= np.random.normal(0,1,size = 1000000)

In [3]:
np.min(x)

-4.778282465271682

In [5]:
np.argmin(x)   argmin   返回最小值的索引值

195729

In [6]:
np.argmax(x)

980866

In [7]:
x[980866]

5.075335752648648

In [8]:
np.max(x)

5.075335752648648

### 排序和使用索引

In [9]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
np.random.shuffle(x)    打乱

In [11]:
x

array([ 9,  0, 10,  8, 15,  1, 12,  6,  5,  7, 11, 14,  3,  2,  4, 13])

In [12]:
np.sort(x)              排序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
X = np.random.randint(10,size=(4,4))

In [28]:
X

array([[3, 9, 5, 0],
       [1, 7, 0, 4],
       [1, 8, 8, 0],
       [4, 0, 3, 9]])

In [30]:
np.sort(X,axis=1)   

array([[0, 3, 5, 9],
       [0, 1, 4, 7],
       [0, 1, 8, 8],
       [0, 3, 4, 9]])

In [17]:
np.sort(X,axis=0)   每一列排序

array([[5, 0, 1, 2],
       [6, 1, 5, 4],
       [7, 4, 8, 6],
       [9, 9, 8, 6]])

In [19]:
x=np.arange(16)

In [20]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
np.random.shuffle(x)

In [22]:
x

array([14,  4, 15, 12,  5, 10,  2,  7,  0, 13,  1,  6,  3,  9,  8, 11])

In [23]:
np.argsort(x)     argsort排序之后显示索引值

array([ 8, 10,  6, 12,  1,  4, 11,  7, 14, 13,  5, 15,  3,  9,  0,  2])

In [25]:
np.partition(x,3)      以一个点 把数组切分 左边都小于x  右边都大于x

array([ 0,  2,  1,  3,  5,  4,  6,  7,  9,  8, 10, 11, 13, 12, 15, 14])

In [26]:
np.argpartition(x,3)  以一个点 把数组切分 左边都小于x  右边都大于x  返回索引值

array([ 8,  6, 10, 12,  4,  1, 11,  7, 13, 14,  5, 15,  9,  3,  2,  0])

In [31]:
X

array([[3, 9, 5, 0],
       [1, 7, 0, 4],
       [1, 8, 8, 0],
       [4, 0, 3, 9]])

In [32]:
np.argsort(X,axis=1)

array([[3, 0, 2, 1],
       [2, 0, 3, 1],
       [3, 0, 1, 2],
       [1, 2, 0, 3]])

In [33]:
np.argsort(X,axis=0)

array([[1, 3, 1, 0],
       [2, 1, 3, 2],
       [0, 2, 0, 1],
       [3, 0, 2, 3]])

In [34]:
np.argpartition(X,2,axis=1)

array([[3, 0, 2, 1],
       [2, 0, 3, 1],
       [3, 0, 2, 1],
       [1, 2, 0, 3]])

In [35]:
x

array([14,  4, 15, 12,  5, 10,  2,  7,  0, 13,  1,  6,  3,  9,  8, 11])

In [36]:
x=np.sort(x)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [37]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [38]:
index = [3,5,8]
x[index]

array([3, 5, 8])

In [40]:
index = np.array([[0,2],
                [1,3]])
x[index]                          将一维向量的值取出来  组成一个矩阵

array([[0, 2],
       [1, 3]])

In [41]:
X=x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## numpy.array的比较

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [50]:
x>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [51]:
x==3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [52]:
x!=3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [53]:
2*x==24-4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [54]:
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
X<6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
np.sum(x<=3)     将true 和 false当做一个元素相加

4

In [59]:
np.any(x == 0)  查看是否有为0元素

True

In [60]:
np.count_nonzero(x<3)

3

In [61]:
np.all(x>0)

False

In [63]:
np.sum(X%2 == 0,axis=1)   每一行多少个偶数

array([2, 2, 2, 2])

In [64]:
np.sum(X%2 == 0,axis=0)每一列多少偶数

array([4, 0, 4, 0])

In [65]:
np.all(X>0,axis=1)

array([False,  True,  True,  True])

In [66]:
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [68]:
np.sum((x>3) & (x<10))

6

In [69]:
np.sum((x%2==0)|(x>10))

11

In [71]:
np.sum(~(x==0))

15

In [72]:
x[x<5]

array([0, 1, 2, 3, 4])