# Scikit-learn中的Scaler

In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris  = datasets.load_iris()


In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target)

# scikit-learn中的StandScaler

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
standardScaler = StandardScaler()


In [8]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
standardScaler.mean_

array([5.88660714, 3.02767857, 3.86517857, 1.22678571])

In [22]:
X_test_standard = standardScaler.fit(X_test)

In [12]:
standardScaler.scale_

array([0.81058792, 0.43593287, 1.71629323, 0.74414166])

In [13]:
standardScaler.transform(X_train)

array([[-1.09378282, -1.66924455, -0.32930187, -0.30476148],
       [-0.10684485, -0.75167209,  0.13681894, -0.30476148],
       [-1.09378282,  1.08347285, -1.49460391, -1.24544259],
       [ 0.26325689, -0.06349274,  0.42814445,  0.23277058],
       [ 1.74366386, -0.29288585,  1.41865118,  0.77030264],
       [ 2.23713285, -0.9810652 ,  1.76824179,  1.44221772],
       [-0.84704833,  1.08347285, -1.3780737 , -1.3798256 ],
       [-1.21715007,  0.16590038, -1.3780737 , -1.3798256 ],
       [-1.09378282,  0.85407973, -1.3198086 , -1.11105957],
       [ 1.00346038,  0.16590038,  1.01079547,  1.57660073],
       [-0.23021209, -0.9810652 , -0.21277167, -0.30476148],
       [-0.97041558,  1.7716522 , -1.14501329, -1.11105957],
       [-1.34051732, -0.06349274, -1.4363388 , -1.24544259],
       [-0.60031384,  1.54225908, -1.3780737 , -1.3798256 ],
       [-0.84704833,  0.85407973, -1.4363388 , -1.3798256 ],
       [-1.34051732,  0.16590038, -1.3198086 , -1.3798256 ],
       [ 0.50999139, -0.

In [29]:
X_test =standardScaler.transform(X_test)

In [15]:
X_train =standardScaler.transform(X_train)

In [16]:
standardScaler.transform(X_test)

array([[-1.58725181,  0.85407973, -1.4363388 , -1.24544259],
       [-1.46388456,  0.3952935 , -1.49460391, -1.3798256 ],
       [ 0.38662414, -0.52227897,  0.54467466,  0.77030264],
       [ 2.1137656 , -0.06349274,  1.59344649,  1.17345169],
       [ 1.62029661,  0.3952935 ,  1.24385588,  0.77030264],
       [ 0.38662414,  0.85407973,  0.89426527,  1.44221772],
       [-0.35357934, -0.29288585, -0.15450656,  0.09838756],
       [-1.09378282,  0.85407973, -1.3780737 , -1.3798256 ],
       [ 0.63335863, -0.75167209,  0.83600017,  0.90468565],
       [-1.21715007, -1.43985144, -0.32930187, -0.30476148],
       [ 1.8670311 , -0.52227897,  1.30212098,  0.90468565],
       [ 0.0165224 ,  0.3952935 ,  0.54467466,  0.77030264],
       [-0.47694659,  1.08347285, -1.49460391, -1.3798256 ],
       [-0.97041558, -1.21045832, -0.50409718, -0.17037847],
       [ 0.63335863, -0.52227897,  1.01079547,  1.3078347 ],
       [-0.35357934, -0.06349274,  0.13681894,  0.09838756],
       [-0.60031384,  2.

In [17]:
 from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [19]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [31]:
X_test_standard = np.array(X_test_standard).reshape(1,-1)

In [32]:
knn_clf.score(X_test_standard,y_test)

TypeError: float() argument must be a string or a number, not 'StandardScaler'

In [22]:
knn_clf.score(X_test,y_test)

0.2894736842105263