# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_spilt

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexes = np.random.permutation(len(X))

In [8]:
shuffle_indexes

array([118,  33,  37,  46, 134,  70,   1, 113,  69, 145,   7, 142,  74,
       105,  90,  25,  15, 127, 144,  62,  13,  99,  19,  58,  20,   9,
       103, 106,  11,  48, 115,  51,  30,  64, 100,  32,  18, 137, 126,
        75,  40, 133,  87,  26,  91,  97,  36, 141, 120, 114,  28,  29,
       130,   5,  76,  10,  65,  66,   4,  17, 149, 125,  63,  94,  39,
        80, 132,  21, 112,  22,  56,  61,  47,  83, 119,  31, 135, 108,
        82,  78, 148,  68,  54, 138, 139,  95,  93, 101, 146,  67,  79,
        44, 110, 117,  45, 116,   0,   6, 124,  53, 102,  77, 107,   3,
        73,  71,  60,  49,  16,  57,  23,  96, 147, 109,  14,  55,  27,
        41, 140,  38, 123, 131, 136, 111,  81,  92,  43,   8, 121, 104,
        34,   2,  98,  72,  12,  84, 143,  35, 129,  85,  42,  89,  88,
        52, 122,  24,  50, 128,  86,  59])

In [9]:
test_ratio = 0.2
test_size = len(X) * test_ratio

In [10]:
test_size

30.0

In [11]:
test_indexes = shuffle_indexes[:30]
train_indexes = shuffle_indexes[30:]

In [12]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [13]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


## 使用我们的算法


In [14]:

from KNN.model_selection import train_test_spilt

X_train, X_test, y_train, y_test = train_test_spilt(X, y)

X_train, X_test, y_train, y_test = train_test_spilt(X, y, test_size=0.2, random_state=666)


In [15]:
print (X_train.shape)
print (y_train.shape)

(120, 4)
(120,)


In [16]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [17]:
from KNN.KNN_self import KNNclassifier

In [18]:
my_knn_clf = KNNclassifier(k=3)

In [19]:
my_knn_clf.fit(X_train,y_train)

KNN(k=3)

In [22]:
y_predict = my_knn_clf.predict(X_test)

In [23]:
y_predict

array([1, 0, 2, 2, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 2,
       1, 1, 0, 1, 2, 0, 1, 0])

In [24]:
y_test

array([2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 2, 0, 2, 2, 1, 2,
       2, 1, 0, 1, 2, 0, 2, 0])

In [25]:
sum(y_predict == y_test)

22

In [26]:
sum(y_predict == y_test)/len(y_test)

0.7333333333333333

## sklearn中的train_test_split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=666)

In [29]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [30]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
